SubnetJTP/SubnetJTP/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

SubnetJTP/SubnetWeb/urls.py
from django.conf.urls import url
from django.conf.urls import include
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
]

SubnetJTP/SubnetWeb/models.py
from django.db import models

# Create your models here.

SubnetJTP/SubnetWeb/forms.py
import json
from django import forms

class subnetForm(forms.Form):
    NETWORK_CLASS_CHOICES = [
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('ANY', 'No Class (Only Subnet bits)'),
    ]

    SUBNET_MASK_CHOICES = [
    (32, '255.255.255.255 /32'),
    (31, '255.255.255.254 /31'),
    (30, '255.255.255.252 /30'),
    (29, '255.255.255.248 /29'),
    (28, '255.255.255.240 /28'),
    (27, '255.255.255.224 /27'),
    (26, '255.255.255.192 /26'),
    (25, '255.255.255.128 /25'),
    (24, '255.255.255.0 /24'),
    (23, '255.255.254.0 /23'),
    (22, '255.255.252.0 /22'),
    (21, '255.255.248.0 /21'),
    (20, '255.255.240.0 /20'),
    (19, '255.255.224.0 /19'),
    (18, '255.255.192.0 /18'),
    (17, '255.255.128.0 /17'),
    (16, '255.255.0.0 /16'),
    (15, '255.254.0.0 /15'),
    (14, '255.252.0.0 /14'),
    (13, '255.248.0.0 /13'),
    (12, '255.240.0.0 /12'),
    (11, '255.224.0.0 /11'),
    (10, '255.192.0.0 /10'),
    (9, '255.128.0.0 /9'),
    (8, '255.0.0.0 /8'),
    (7, '254.0.0.0 /7'),
    (6, '252.0.0.0 /6'),
    (5, '248.0.0.0 /5'),
    (4, '240.0.0.0 /4'),
    (3, '224.0.0.0 /3'),
    (2, '192.0.0.0 /2'),
    (1, '128.0.0.0 /1'),
    ]

    SUBNET_MASK = {
    '32' : [255, 255, 255, 255],
    '31' : [255, 255, 255, 254],
    '30' : [255, 255, 255, 252],
    '29' : [255, 255, 255, 248],
    '28' : [255, 255, 255, 240],
    '27' : [255, 255, 255, 224],
    '26' : [255, 255, 255, 192],
    '25' : [255, 255, 255, 128],
    '24' : [255, 255, 255, 0],
    '23' : [255, 255, 254, 0],
    '22' : [255, 255, 252, 0],
    '21' : [255, 255, 248, 0],
    '20' : [255, 255, 240, 0],
    '19' : [255, 255, 224, 0],
    '18' : [255, 255, 192, 0],
    '17' : [255, 255, 128, 0],
    '16' : [255, 255, 0, 0],
    '15' : [255, 254, 0, 0],
    '14' : [255, 252, 0, 0],
    '13' : [255, 248, 0, 0],
    '12' : [255, 240, 0, 0],
    '11' : [255, 224, 0, 0],
    '10' : [255, 192, 0, 0],
    '9' : [255, 128, 0, 0],
    '8' : [255, 0, 0, 0],
    '7' : [254, 0, 0, 0],
    '6' : [252, 0, 0, 0],
    '5' : [248, 0, 0, 0],
    '4' : [240, 0, 0, 0],
    '3' : [224, 0, 0, 0],
    '2' : [192, 0, 0, 0],
    '1' : [128, 0, 0, 0],
    }

    class_subnet_dict = {
    }

    class_subnet_dict['ANY'] = []
    class_subnet_dict['A'] = []
    class_subnet_dict['B'] = []
    class_subnet_dict['C'] = []

    for num in reversed(range(1, 33)):
        class_subnet_dict['ANY'].append(num)
        if num >= 8 :
            class_subnet_dict['A'].append(num)
        if num >= 16 :
            class_subnet_dict['B'].append(num)
        if num >= 24 :
            class_subnet_dict['C'].append(num)

    network_class = forms.ChoiceField(choices = NETWORK_CLASS_CHOICES
    , required = True, label = 'Network Class')
    subnet_mask = forms.ChoiceField(choices = SUBNET_MASK_CHOICES
    , required = True, label = 'Subnet Mask')
    ip4_input = forms.GenericIPAddressField(protocol = 'IPv4'
    , required = True, label = 'IPv4 Address')

    classes = json.dumps(NETWORK_CLASS_CHOICES)
    subnets = json.dumps(class_subnet_dict)
    subnets_text = json.dumps(SUBNET_MASK_CHOICES)

SubnetJTP/SubnetWeb/views.py
from django.shortcuts import render
from .forms import subnetForm
import json

def index(request):
    form = subnetForm(request.POST or None)
    info_table = None
    network_table_header = None
    network_table = None
    network_table_limit = 128

    if form.is_valid():
        network_class = form.cleaned_data['network_class']
        subnet_num = int(form.cleaned_data['subnet_mask'])
        ip4_input = form.cleaned_data['ip4_input']
        subnet = form.SUBNET_MASK[str(subnet_num)]
        wildcard_num = 32 - subnet_num

        wildcard = []
        for i in range(0, 4):
            wildcard.append(255 - subnet[i])

        ip4 = []
        for string in ip4_input.split('.') :
            ip4.append(int(string))

        net_addr = []
        for i in range(0, 4):
            net_addr.append(subnet[i] & ip4[i])

        broadcast_addr = net_addr[:]
        for i in range(0, 4):
            broadcast_addr[i] |=  wildcard[i]

        #---------------------------------------------------------------------------------------------------#
        info_table = []
        info_table.append(['IP Address', makeIpString(ip4)])
        info_table.append(['Network Address', makeIpString(net_addr)])
        info_table.append(['Usable Host IP Range', usableHostRange(net_addr, broadcast_addr, subnet_num)])
        info_table.append(['Broadcast Address', makeIpString(broadcast_addr)])
        info_table.append(['Total Number of Hosts', str(2 ** wildcard_num)])
        info_table.append(['Number of Usable Hosts', str(max([(2 ** wildcard_num) - 2, 0]))])
        info_table.append(['Subnet Mask', makeIpString(subnet)])
        info_table.append(['Wildcard Mask', makeIpString(wildcard)])
        info_table.append(['Binary Subnet Mask', makeBinaryIpString(subnet)])
        info_table.append(['Binary Wildcard Mask', makeBinaryIpString(wildcard)])
        info_table.append(['IP Class', ipClass(ip4)])
        info_table.append(['IP Class (For this calculation)', ipClassForCal(network_class)])
        info_table.append(['CIDR Notation', '/' + str(subnet_num)])
        info_table.append(['IP Type', ipType(ip4)])
        info_table.append(['Short', makeIpString(ip4) + ' /' + str(subnet_num)])
        info_table.append(['Binary ID', makeBinaryValue(ip4)])
        info_table.append(['Integer ID', str(makeIntValue(ip4))])
        info_table.append(['Hex ID', makeHexValue(ip4)])
        #---------------------------------------------------------------------------------------------------#
        network_table = []
        entry_count = 0
        start_value = 0
        end_value = 0x100000000
        step_value = makeIntValue(wildcard) + 1

        if network_class == 'A':
            start_value = makeIntValue(ip4) & 0xff000000
            end_value = start_value + 0x01000000
        elif network_class == 'B':
            start_value = makeIntValue(ip4) & 0xffff0000
            end_value = start_value + 0x00010000
        elif network_class == 'C':
            start_value = makeIntValue(ip4) & 0xffffff00
            end_value = start_value + 0x00000100

        current_value = start_value
        #print(makeIpString(ip4) + " / " + str(makeIntValue(ip4)) + " / " + intToIp(start_value) + " / " + intToIp(end_value) + " / " + intToIp(step_value))

        while entry_count < network_table_limit and current_value < end_value :
            network_addr = intToIp(current_value)
            usable_range = ""
            broad_addr = ""

            if subnet_num == 32 :
                usable_range = "None"
                broad_addr = network_addr[:]
            elif subnet_num == 31 :
                usable_range = "None"
                broad_addr = intToIp(current_value + 1)
            else :
                usable_range = intToIp(current_value + 1) + " - " + intToIp(current_value + step_value - 2)
                broad_addr = intToIp(current_value + step_value - 1)

            network_table.append([network_addr, usable_range, broad_addr])
            current_value += step_value
            entry_count += 1

            if current_value >= end_value :
                network_table_header = "All Possible '/" + str(subnet_num) + "' Networks"
            else :
                network_table_header = "First " + str(network_table_limit) +" Possible '/" + str(subnet_num) + "' Networks"
        #---------------------------------------------------------------------------------------------------#


    context = {
    'form' : form,
    'info_table' : info_table,
    'network_table_header' : network_table_header,
    'network_table' : network_table,
    }
    template = 'index.html'
    return render(request, template, context)

def makeIpString(value):
    ans = ''
    if(len(value) > 0):
        ans = str(value[0])
        if(len(value) > 1):
            for i in range(1, len(value)):
                ans += ('.' + str(value[i]))
    return ans

def usableHostRange(net_addr, broadcast_addr, subnet_num):
    if subnet_num >= 31 :
        return 'None'
    else :
        min_addr = net_addr[:]
        min_addr[3] += 1

        max_addr = broadcast_addr[:]
        max_addr[3] -= 1

        return makeIpString(min_addr) + " - " + makeIpString(max_addr)

def makeBinaryIpString(value):
    ans = ''
    if(len(value) > 0):
        ans = '{0:08b}'.format(value[0])
        if(len(value) > 1):
            for i in range(1, len(value)):
                ans += ('.' + '{0:08b}'.format(value[i]))
    return ans

def makeIntValue(value):
    ans = 0
    if(len(value) > 0):
        for i in range(0, len(value)):
            ans *= 256
            ans += value[i]
    return ans

def makeBinaryValue(value):
    intValue = makeIntValue(value)
    return '{0:#034b}'.format(intValue)

def makeHexValue(value):
    intValue = makeIntValue(value)
    return '{0:#010x}'.format(intValue)

def ipClass(value):
    if value[0] <= 127 :
        return 'A'
    elif value[0] <= 191 :
        return 'B'
    elif value[0] <= 223 :
        return 'C'
    elif value[0] <= 239 :
        return 'D'
    else:
        return 'E'

def ipClassForCal(value):
    if value == 'ANY' :
        return 'None'
    else :
        return value

def ipType(value):
    if value[0] == 10 :
        return 'Private'
    elif value[0] == 172 and value[1] >= 16 and value[1] <= 31 :
        return 'Private'
    elif value[0] == 192 and value[1] == 168 :
        return 'Private'
    else :
        return 'Public'

def intToIp(value):
    ans = []
    ans.append((value & 0xff000000) >> 24)
    ans.append((value & 0x00ff0000) >> 16)
    ans.append((value & 0x0000ff00) >> 8)
    ans.append(value & 0x000000ff)
    return makeIpString(ans)

SubnetJTP/SubnetWeb/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>IP Subnet Calculator</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    {% block header %}
    {% endblock %}
  </head>
  <body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

SubnetJTP/SubnetWeb/templates/index.html
{% extends "base.html" %}
{% load bootstrap %}
{% load static from staticfiles %}

{% block header %}
    <link rel="stylesheet" href="{% static "index.css" %}">
{% endblock %}

{% block content %}
    <br>

    <div class="row">
        <div class="col-2 .col-md-4 .col-lg-5"></div>
        <div class="col-8 .col-md-4 .col-lg-2">
            <div class="header clearfix">
                <h3 class="text-muted">IP Address Subnet Calculator</h3>
            </div>
            <hr>
        </div>
    </div>

    <br>

    {% if form %} <!--Form-->
        <div class="row">
            <div class="col-2 .col-md-4 .col-lg-5"></div>
            <div class="col-8 .col-md-4 .col-lg-2">
                <form method='POST' action=''>{% csrf_token %}
                    {{ form|bootstrap }}
                    <input type="submit" value="Calculate" class = 'btn btn-success' />
                </form>
            </div>
        </div>
    {% endif %}

    <br>
    <br>

    {% if info_table %} <!--Info Table-->
        <div class="row">
            <div class="col-2 .col-md-4 .col-lg-5"></div>
            <div class="col-8 .col-md-4 .col-lg-2">
                <h3>Result</h3>
                <table class="table table-striped">
                    <tbody>
                        {% for row in info_table %}
                            <tr>
                                {% for data in row %}
                                    <td>{{ data }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}

    <br>
    <br>

    {% if network_table %} <!--Network Table-->
        <div class="row">
            <div class="col-2 .col-md-4 .col-lg-5"></div>
            <div class="col-8 .col-md-4 .col-lg-2">
                {% if network_table_header %}
                    <h3>{{ network_table_header }}</h3>
                {% endif %}
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th>Network Address</th>
                            <th>Usable Host Range</th>
                            <th>Broadcast Address</th>
                        </tr>
                        {% for row in network_table %}
                            <tr>
                                {% for data in row %}
                                    <td>{{ data }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}

    <br>

    <div class="row">
        <div class="col-2 .col-md-4 .col-lg-5"></div>
        <div class="col-8 .col-md-4 .col-lg-2">
            <hr>
            <h5 class="text-muted">Create by Jittapat Nawarattanapong</h5>
        </div>
    </div>

    <br>

{% endblock %}

{% block js %}
    <script language="javascript">
        $('#id_network_class').change(function() {populateSubnet(this)});
        subnets = {{ form.subnets | safe }}
        classes = {{ form.classes | safe}};
        subnets_text = {{form.subnets_text | safe }}
        populateNetwork();
        $("#id_subnet_mask").empty();
        $("#id_subnet_mask").append('<option value="" disabled selected>First select a network class</option>');

        function populateNetwork() {
            $('#id_network_class').empty();
            $("#id_network_class").append('<option value="" disabled selected>Select a network class</option>');
            $.each(classes, function(v) {
                $('#id_network_class')
                    .append($("<option></option>")
                    .attr("value", classes[v][0])
                    .text(classes[v][1]));
            });
        }
        function populateSubnet(event) {
            network_class = $("#id_network_class option:selected").attr("value");
            $("#id_subnet_mask").empty();
            $("#id_subnet_mask").append('<option value="" disabled selected>Select a subnet mask</option>');
            for (let [nc, class_subnet_dict] of Object.entries(subnets)) {
                if (nc == network_class) {
                    for (sn in class_subnet_dict) {
                        $('#id_subnet_mask')
                            .append($("<option></option>")
                                .attr("value", class_subnet_dict[sn])
                                .text(findSubnetText(class_subnet_dict[sn])));
                    }
                }
            }
        }
        function findSubnetText(sn_input){
            sn_input_str = sn_input.toString();
            ans = "Not found"

            $.each(subnets_text, function(i, v) {
                value_str = v[0].toString();
                if(value_str === sn_input_str){
                    ans = v[1].toString();
                }
            });

            return ans;
        }
    </script>
{% endblock %}